version: 2

sources:
  - name: google_analytics_sample
    description : "Google Analytics Sample Dataset : The dataset provides 12 months (August 2016 to August 2017) of obfuscated Google Analytics 360 data from the Google Merchandise Store , a real ecommerce store that sells Google-branded merchandise in BigQuery."
    database: bigquery-public-data
    schema: google_analytics_sample
    description: "Sessions data from Google Analytics, you can find schema details here: https://support.google.com/analytics/answer/3437719?hl=en"
    tables:
      - name: ga_sessions
        identifier : ga_sessions_*
        
models:
  - name: src_analytics
    description: Description of src_analytics 

  - name: actions
    description: Description of actions

  - name: products
    description: Description of products

  - name: men_tshirts
    description: Description of men_tshirts

  - name: conversion_rate
    description: Description of conversion rate

  - name: best_selling
    description: Description of best selling

  - name: moving_average
    description: Description of moving_average
